### ISSUE TITLE
DigitClassifier App keeps stopping

### ISSUE THREAD

**Issue by sumeetssaurav** [googlesamples/mediapipe#203]
Hii @PaulTR ,

I am trying to deploy the digit classifier app, however, after successful building, the app keeps stopping. 
![Screenshot_20230808_234632](https://github.com/googlesamples/mediapipe/assets/13672595/3b20b661-07a7-4cab-b753-f9688682b286)

I am following the code sample provided in the repository.

**Comment by PaulTR** [comment]
Hey, so this is for a codelab that hasn't been published yet :)

Also I'll need you to provide the log for that crash to determine what could be an issue.

Thanks!

**Comment by sumeetssaurav** [comment]
Hii @PaulTR 

Thankx for the quick reply. Here is the logcat. BTW, when will be the codelab released??

FATAL EXCEPTION: main
                                                                                                    Process: com.google.mediapipe.codelab.digitclassifier, PID: 17517
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>(BaseVisionTaskApi.java:37)
                                                                                                    	at com.google.mediapipe.tasks.vision.imageclassifier.ImageClassifier.createFromOptions(ImageClassifier.java:168)
                                                                                                    	at com.google.mediapipe.codelab.digitclassifier.DigitClassifierHelper.setupDigitClassifier(DigitClassifierHelper.kt:54)
                                                                                                    	at com.google.mediapipe.codelab.digitclassifier.DigitClassifierHelper.<init>(DigitClassifierHelper.kt:39)
                                                                                                    	at com.google.mediapipe.codelab.digitclassifier.DigitCanvasFragment.onViewCreated(DigitCanvasFragment.kt:53)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8076)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by PaulTR** [comment]
Sounds like you don't have the dependency in the app - I'm guessing there should be some kind of message when trying to sync since the dependency is in the build.gradle.kts file. I ran everything on Giraffe.

Waiting on approvals for the codelab, so likely won't dig too far into this since it isn't official/potentially finished yet. You might just have to wait until the codelab to follow step-by-step :)

**Comment by PaulTR** [comment]
Going to close this out since it's not the most relevant without the instructions out yet. The PR for the codelab is up, so hopefully this week.

**Comment by sumeetssaurav** [comment]
Hii @PaulTR 

I followed the Codelab released yesterday and still facing the same issue. 

Thank You

**Comment by PaulTR** [comment]
What device are you using? And can you upload your app to github to check out?
