### ISSUE TITLE
Mediaipe image generator app crashes during initialization

### ISSUE THREAD

**Issue by zmlee0514** [googlesamples/mediapipe#268]
Hello, I have generated images on the Galaxy S23 ultra through the [doc](https://developers.google.com/mediapipe/solutions/vision/image_generator/android) successfully. But when I tried it on the HTC U23 Pro without changing anything, It crashed once I clicked the "initialize" button.

The messages from logcat:
```---------------------------- PROCESS STARTED (13277) for package com.google.mediapipe.examples.imagegeneration ----------------------------
2023-10-30 10:59:31.538 13277-13277 ziparchive              com...pipe.examples.imagegeneration  W  Unable to open '/data/app/~~ZcH5iuUU6afdm6UAuSoXrA==/com.google.mediapipe.examples.imagegeneration-JqvqUC92wk41qMMTVmKsKA==/base.dm': No such file or directory
2023-10-30 10:59:31.538 13277-13277 ziparchive              com...pipe.examples.imagegeneration  W  Unable to open '/data/app/~~ZcH5iuUU6afdm6UAuSoXrA==/com.google.mediapipe.examples.imagegeneration-JqvqUC92wk41qMMTVmKsKA==/base.dm': No such file or directory
2023-10-30 10:59:31.684 13277-13277 Perf                    com...pipe.examples.imagegeneration  I  Connecting to perf service.
2023-10-30 10:59:31.689 13277-13277 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  ANGLE Developer option for 'com.google.mediapipe.examples.imagegeneration' set to: 'default'
2023-10-30 10:59:31.690 13277-13277 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  ANGLE GameManagerService for com.google.mediapipe.examples.imagegeneration: false
2023-10-30 10:59:31.690 13277-13277 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  Updatable production driver is not supported on the device.
2023-10-30 10:59:31.693 13277-13277 NetworkSecurityConfig   com...pipe.examples.imagegeneration  D  No Network Security Config specified, using platform default
2023-10-30 10:59:31.694 13277-13277 NetworkSecurityConfig   com...pipe.examples.imagegeneration  D  No Network Security Config specified, using platform default
2023-10-30 10:59:31.733 13277-13277 AppCompatDelegate       com...pipe.examples.imagegeneration  D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2023-10-30 10:59:31.776 13277-13277 Compatibil...geReporter com...pipe.examples.imagegeneration  D  Compat change id reported: 210923482; UID 10216; state: ENABLED
2023-10-30 10:59:31.779 13277-13277 imagegeneration         com...pipe.examples.imagegeneration  W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2023-10-30 10:59:31.789 13277-13277 imagegeneration         com...pipe.examples.imagegeneration  W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2023-10-30 10:59:31.835 13277-13298 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  QUALCOMM build                   : c3c6e0a, Ifa69ebc583
                                                                                                    Build Date                       : 04/24/23
                                                                                                    OpenGL ES Shader Compiler Version: EV031.36.08.19
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-10-30 10:59:31.835 13277-13298 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Build Config                     : S P 12.1.1 AArch64
2023-10-30 10:59:31.835 13277-13298 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-10-30 10:59:31.835 13277-13298 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Driver Version                   : 0615.60
2023-10-30 10:59:31.840 13277-13298 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  PFP: 0x016dc109, ME: 0x00000000
2023-10-30 10:59:31.861 13277-13298 OpenGLRenderer          com...pipe.examples.imagegeneration  E  Unable to match the desired swap behavior.
2023-10-30 10:59:31.877 13277-13298 Parcel                  com...pipe.examples.imagegeneration  W  Expecting binder but got null!
2023-10-30 10:59:37.104 13277-13308 ProfileInstaller        com...pipe.examples.imagegeneration  D  Installing profile for com.google.mediapipe.examples.imagegeneration
2023-10-30 10:59:37.578 13277-13298 OpenGLRenderer          com...pipe.examples.imagegeneration  E  Unable to match the desired swap behavior.
2023-10-30 10:59:37.593 13277-13298 Parcel                  com...pipe.examples.imagegeneration  W  Expecting binder but got null!
2023-10-30 10:59:37.687 13277-13287 imagegeneration         com...pipe.examples.imagegeneration  I  Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
2023-10-30 10:59:38.083 13277-13298 OpenGLRenderer          com...pipe.examples.imagegeneration  D  endAllActiveAnimators on 0xb40000754317e5d0 (RippleDrawable) with handle 0xb4000074531882c0
2023-10-30 10:59:38.893 13277-13322 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634778.892962   13322 diffuser.cc:81] Environment created
2023-10-30 10:59:41.579 13277-13322 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634781.579097   13322 diffuser.cc:89] TextGuidance is created
2023-10-30 10:59:41.611 13277-13322 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634781.611672   13322 diffuser.cc:94] Copier is created
2023-10-30 11:00:00.405 13277-13290 System                  com...pipe.examples.imagegeneration  W  A resource failed to call close. 
2023-10-30 11:00:02.489 13277-13322 native                  com...pipe.examples.imagegeneration  E  E0000 00:00:1698634802.489948   13322 diffuser_gpu.cc:88] UNKNOWN: Failed to create 2D texture (clCreateImage): Invalid image size
2023-10-30 11:00:02.490 13277-13319 native                  com...pipe.examples.imagegeneration  E  E0000 00:00:1698634802.490127   13319 calculator_graph.cc:875] INTERNAL: CalculatorGraph::Run() failed: 
                                                                                                    Calculator::Open() for node "mediapipe_tasks_vision_image_generator_imagegeneratorgraph__StableDiffusionIterateCalculator" failed: ; RET_CHECK failure (mediapipe/tasks/cc/vision/image_generator/diffuser/stable_diffusion_iterate_calculator.cc:237) context_
2023-10-30 11:00:02.501 13277-13319 AndroidRuntime          com...pipe.examples.imagegeneration  E  FATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: com.google.mediapipe.examples.imagegeneration, PID: 13277
                                                                                                    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed: 
                                                                                                    Calculator::Open() for node "mediapipe_tasks_vision_image_generator_imagegeneratorgraph__StableDiffusionIterateCalculator" failed: ; RET_CHECK failure (mediapipe/tasks/cc/vision/image_generator/diffuser/stable_diffusion_iterate_calculator.cc:237) context_
                                                                                                    	at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
                                                                                                    	at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:464)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:74)
                                                                                                    	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:167)
                                                                                                    	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:96)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.ImageGenerationHelper.initializeImageGenerator(ImageGenerationHelper.kt:32)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.diffusion.DiffusionViewModel$initializeImageGenerator$3.invokeSuspend(DiffusionViewModel.kt:66)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e4461be, Dispatchers.Default]
2023-10-30 11:00:02.543 13277-13319 Process                 com...pipe.examples.imagegeneration  I  Sending signal. PID: 13277 SIG: 9
---------------------------- PROCESS ENDED (13277) for package com.google.mediapipe.examples.imagegeneration ----------------------------
---------------------------- PROCESS STARTED (13383) for package com.google.mediapipe.examples.imagegeneration ----------------------------
2023-10-30 11:00:02.699 13383-13383 Compatibil...geReporter com...pipe.examples.imagegeneration  D  Compat change id reported: 171979766; UID 10216; state: ENABLED
2023-10-30 11:00:02.711 13383-13383 ziparchive              com...pipe.examples.imagegeneration  W  Unable to open '/data/app/~~ZcH5iuUU6afdm6UAuSoXrA==/com.google.mediapipe.examples.imagegeneration-JqvqUC92wk41qMMTVmKsKA==/base.dm': No such file or directory
2023-10-30 11:00:02.711 13383-13383 ziparchive              com...pipe.examples.imagegeneration  W  Unable to open '/data/app/~~ZcH5iuUU6afdm6UAuSoXrA==/com.google.mediapipe.examples.imagegeneration-JqvqUC92wk41qMMTVmKsKA==/base.dm': No such file or directory
2023-10-30 11:00:02.857 13383-13383 Perf                    com...pipe.examples.imagegeneration  I  Connecting to perf service.
2023-10-30 11:00:02.863 13383-13383 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  ANGLE Developer option for 'com.google.mediapipe.examples.imagegeneration' set to: 'default'
2023-10-30 11:00:02.864 13383-13383 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  ANGLE GameManagerService for com.google.mediapipe.examples.imagegeneration: false
2023-10-30 11:00:02.864 13383-13383 GraphicsEnvironment     com...pipe.examples.imagegeneration  V  Updatable production driver is not supported on the device.
2023-10-30 11:00:02.867 13383-13383 NetworkSecurityConfig   com...pipe.examples.imagegeneration  D  No Network Security Config specified, using platform default
2023-10-30 11:00:02.868 13383-13383 NetworkSecurityConfig   com...pipe.examples.imagegeneration  D  No Network Security Config specified, using platform default
2023-10-30 11:00:02.910 13383-13383 AppCompatDelegate       com...pipe.examples.imagegeneration  D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2023-10-30 11:00:02.943 13383-13383 Compatibil...geReporter com...pipe.examples.imagegeneration  D  Compat change id reported: 210923482; UID 10216; state: ENABLED
2023-10-30 11:00:02.946 13383-13383 imagegeneration         com...pipe.examples.imagegeneration  W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2023-10-30 11:00:02.956 13383-13383 imagegeneration         com...pipe.examples.imagegeneration  W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2023-10-30 11:00:03.005 13383-13403 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  QUALCOMM build                   : c3c6e0a, Ifa69ebc583
                                                                                                    Build Date                       : 04/24/23
                                                                                                    OpenGL ES Shader Compiler Version: EV031.36.08.19
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-10-30 11:00:03.005 13383-13403 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Build Config                     : S P 12.1.1 AArch64
2023-10-30 11:00:03.005 13383-13403 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-10-30 11:00:03.005 13383-13403 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  Driver Version                   : 0615.60
2023-10-30 11:00:03.010 13383-13403 AdrenoGLES-0            com...pipe.examples.imagegeneration  I  PFP: 0x016dc109, ME: 0x00000000
2023-10-30 11:00:03.030 13383-13403 OpenGLRenderer          com...pipe.examples.imagegeneration  E  Unable to match the desired swap behavior.
2023-10-30 11:00:03.048 13383-13403 Parcel                  com...pipe.examples.imagegeneration  W  Expecting binder but got null!
2023-10-30 11:00:08.829 13383-13415 ProfileInstaller        com...pipe.examples.imagegeneration  D  Installing profile for com.google.mediapipe.examples.imagegeneration
```

Compared with the log produced by S23, the app might crash when creating Unet.
The part of initialization logs of S23:
```
2023-10-30 10:55:21.065 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634521.065546   19824 diffuser.cc:81] Environment created
2023-10-30 10:55:22.434 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634522.434009   19824 diffuser.cc:89] TextGuidance is created
2023-10-30 10:55:22.451 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634522.451636   19824 diffuser.cc:94] Copier is created
2023-10-30 10:55:29.431 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634529.431868   19824 diffuser.cc:101] UNet is created
2023-10-30 10:55:29.449 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634529.449321   19824 diffuser.cc:105] DiffusionStepper is created
2023-10-30 10:55:31.971 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634531.971300   19824 diffuser.cc:110] Decoder is created
2023-10-30 10:55:31.971 19569-19824 native                  com...pipe.examples.imagegeneration  I  I0000 00:00:1698634531.971546   19824 diffuser.cc:123] latent_copy is created
```

Does anyone know how to fix it? Or the CPU of HTC U23 pro(Snapdragon 7 gen 1) is not supported?

**Comment by PaulTR** [comment]
I'll forward this up the chain to see if anyone has any insight. Thanks for the report!

**Comment by PaulTR** [comment]
Alright a bug is logged for this, so I'm going to close the issue for now. Basically we've tested with Samsungs and Pixels, but are constantly putting more work into fixing these sorts of cases as they come up :) Each manufacturer does some weird stuff with their devices, so it gets messy :)
