### ISSUE TITLE
Unexpected crash when no face detected for a while

### ISSUE THREAD

**Issue by mirjalal** [googlesamples/mediapipe#314]
I have run example android app (without making any changes in the original codebase) in a real device (samsung a53) & put the device on the table without doing anything neither with app nor phone. I waited almost a minute and then crash occurred. Here is the logcat output:

```
FATAL EXCEPTION: main
	Process: com.google.mediapipe.examples.facelandmarker, PID: 7260
	java.lang.IllegalStateException: The specified message queue synchronization  barrier token has not been posted or has already been removed.
		at android.os.MessageQueue.removeSyncBarrier(MessageQueue.java:528)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3233)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11197)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
		at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
		at android.view.Choreographer.doFrame(Choreographer.java:1055)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
		at android.os.Handler.handleCallback(Handler.java:958)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:230)
		at android.os.Looper.loop(Looper.java:319)
		at android.app.ActivityThread.main(ActivityThread.java:8893)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by foreverliu** [comment]
I also encountered
