### ISSUE TITLE
App Crash wile using the Image Generation Sample on android

### ISSUE THREAD

**Issue by BraveEvidence** [googlesamples/mediapipe#333]
I am using the[ image generation sample](https://github.com/googlesamples/mediapipe/tree/main/examples/image_generation) and tried running on my android device

Below is the error 

 F```
ATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: com.google.mediapipe.examples.imagegeneration, PID: 29768
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_image_generator_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.<clinit>(ImageGenerator.java:84)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.ImageGenerationHelper.initializeImageGenerator(ImageGenerationHelper.kt:32)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.diffusion.DiffusionViewModel$initializeImageGenerator$3.invokeSuspend(DiffusionViewModel.kt:66)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@441c5cb, Dispatchers.Default]
2024-03-08 16:30:34.746 29768-29852 Process         
```


I have all the required models in my assets folder. check below screenshot
<img width="341" alt="Screenshot 2024-03-08 at 4 38 09 PM" src="https://github.com/googlesamples/mediapipe/assets/24708929/532f5b27-a9a3-4825-8999-4c4ce5f125da">


I downloaded runwayml/stable-diffusion-v1-5 from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt) 

I did installed required python dependencies

`pip install torch typing_extensions numpy Pillow requests pytorch_lightning absl-py`

I ran [this](https://github.com/googlesamples/mediapipe/blob/main/tools/image_generator_converter/convert.py) python script as well using `python3 convert.py --ckpt_path <ckpt_path> --output_path <output_path>`

and generate all the required files and copied all those generated files using adb 


Check below screenshot of the same


<img width="602" alt="Screenshot 2024-03-08 at 4 41 12 PM" src="https://github.com/googlesamples/mediapipe/assets/24708929/83abcfa7-d08e-4a73-a32b-e549d3706cee">


Once I installed the app from the sample and click StandAlone Generation button and as soon as I click Initialise button I get above error

Same thing happens when I click Generation with Plugins & Generation with Lora weights


I am using Android 12 on Samsung M01 device

What am I missing?

**Comment by SC2Vivern** [comment]
Adding this to the app build.gradle fixed it for me
```
android {
    ...
    defaultConfig {
        ...
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }
}
```
