### ISSUE TITLE
    kotlin.UninitializedPropertyAccessException: lateinit property gestureRecognizerHelper has not been initialized

### ISSUE THREAD

**Issue by javaservlets** [googlesamples/mediapipe#36]
Hi: using AS Eel and the defaults but package com.google.mediapipe.examples.gesturerecognizer.fragment throws 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.examples.gesturerecognizer, PID: 6318
    kotlin.UninitializedPropertyAccessException: lateinit property gestureRecognizerHelper has not been initialized
        at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment$initBottomSheetControls$7.onItemSelected(CameraFragment.kt:235)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/tflite: Initialized TensorFlow Lite runtime.
W/libc: Access denied finding property "ro.mediatek.platform"
W/libc: Access denied finding property "ro.chipname"
W/libc: Access denied finding property "ro.hardware.chipname"
I/tflite: Created TensorFlow Lite XNNPACK delegate for CPU.
I/CameraManagerGlobal: Connecting to camera service
D/CameraRepository: Added camera: 0
I/Process: Sending signal. PID: 6318 SIG: 9

on a pixel 7.

**Comment by javaservlets** [comment]
Thanks Paul for your very prompt turn-around! I don't have my pixel 7 with me now but I've verified on my Galaxy 22 that this is no longer an issue in the today's build.

For the sake of thoroughness, I verified that the previous build indeed threw the same error on this Galaxy 22. 

Ie, I believe this issue can be closed.

Thanks again, 
Robbie
