### ISSUE TITLE
Exception in HandLandmarker sample: lateinit property handLandmarkerHelper has not been initialized

### ISSUE THREAD

**Issue by pritam-ghosh-dev** [googlesamples/mediapipe#39]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.examples.handlandmarker, PID: 22940
    kotlin.UninitializedPropertyAccessException: lateinit property handLandmarkerHelper has not been initialized
        at com.google.mediapipe.examples.handlandmarker.fragment.CameraFragment$initBottomSheetControls$9.onItemSelected(CameraFragment.kt:249)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:979)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:968)
        at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:932)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)

I got this error on my OnePlus 9R device. I can see handLandmarkerHelper has been initialized in onViewCreated() via concurrent executor. That's the reason of the crash I guess. Is it possible to initialize it on the main thread?

**Comment by PaulTR** [comment]
Hi Pritam! To confirm, are you using the latest from the main branch? We actually just put in a fix for this today :) If so, I'll take another look at it tomorrow. Thanks.

**Comment by PaulTR** [comment]
Oh! Actually, this is for the hand landmarker - I fixed it with gesture recognition today. I'll get this updated tomorrow :) Thanks for the heads up!

**Comment by pritam-ghosh-dev** [comment]
thanks for the fix confirmation. (:
