### ISSUE TITLE
Fail to initialize gesture recognizer

### ISSUE THREAD

**Issue by Dakyz** [googlesamples/mediapipe#73]
If start gesture recognizer app on arm64-v8a device so everything is OK. But starting on armeabi-v7a device (Android version is the same and equals to 11) makes facing to some problems:
```
E/tflite: The supplied buffer is not 4-bytes aligned
E/tflite: The model allocation is null/empty
E/native: E20221114 20:29:51.589087  3371 graph.cc:472] Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
W/System.err: com.google.mediapipe.framework.MediaPipeException: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
W/System.err:     at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
W/System.err:     at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:336)
W/System.err:     at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:71)
W/System.err:     at com.google.mediapipe.tasks.vision.gesturerecognizer.GestureRecognizer.createFromOptions(GestureRecognizer.java:194)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.setupGestureRecognizer(GestureRecognizerHelper.kt:95)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.<init>(GestureRecognizerHelper.kt:50)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.onViewCreated$lambda-4(CameraFragment.kt:147)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.$r8$lambda$xiZI6LDAjMBw-J7vyrjSe_CLWo0(Unknown Source:0)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment$$ExternalSyntheticLambda13.run(Unknown Source:2)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
E/GestureRecognizerHelper 56784282: MP Task Vision failed to load the task with error: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
```
I guess the error depends on [device arch](https://android.googlesource.com/platform/external/tensorflow/+/refs/heads/android-s-beta-5/tensorflow/lite/model_test.cc#91). What can you advice in this situation?

**Comment by jenperson** [comment]
Since this sounds like an issue for MediaPipe and not these samples in particular, can you please [post your issue on the MediaPipe repo](https://github.com/google/mediapipe/issues)? That's the best place to get support. Thank you!
