### ISSUE TITLE
audio_classification_live_stream - Python

### ISSUE THREAD

**Issue by sbyintech** [googlesamples/mediapipe#80]
Hi,

I got the following error:

```
Traceback (most recent call last):  
 File "...\mediapipe\examples\audio_classifier\python\audio_classification_live_stream\classify.py", line 134, in <module>
    main()  
 File "...\mediapipe\examples\audio_classifier\python\audio_classification_live_stream\classify.py", line 129, in main
    run(args.model, int(args.maxResults), float(args.scoreThreshold),  
File "...\mediapipe\examples\audio_classifier\python\audio_classification_live_stream\classify.py", line 57, in run
    classifier = audio.AudioClassifier.create_from_options(options)
 File "...\mediapipe\examples\audio_classifier\python\audio_classification_live_stream\venv\lib\site-packages\mediapipe\tasks\python\audio\audio_classifier.py", line 204, in create_from_options
    return cls(  
 File "...\mediapipe\examples\audio_classifier\python\audio_classification_live_stream\venv\lib\site-packages\mediapipe\tasks\python\audio\core\base_audio_task_api.py", line 64, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)

RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: mediapipe::tasks::audio::audio_classifier::AudioClassifierGraph; Unable to find Calculator "mediapipe.tasks.audio.audio_classifier.AudioClassifierGraph"

Process finished with exit code 1
```

I use PyCharm and Windows 10 
I tried with Python 3.9 and 3.10
I tried the provided code and I also tried to use downloaded models:

```
base_options = mp.tasks.BaseOptions(model_asset_path=model)
base_options = mp.tasks.BaseOptions(model_asset_path='lite-model_yamnet_classification_tflite_1.tflite')
base_options = mp.tasks.BaseOptions(model_asset_path='yamnet_audio_classifier_with_metadata.tflite')
```

**Comment by PaulTR** [comment]
Hey sbyintech! So I just asked about this and apparently we haven't gotten Windows support fully in yet. Your best bet would be to use Colab to work through the samples since they're all tested there. We should have external file support relatively soon for Windows.
